package com.example.torrentorv2

import org.json.JSONObject
import java.net.URLEncoder

data class SearchResult(
    val identifier: String,
    val title: String,
    val mediatype: String,
    val downloadUrl: String,
    val pageUrl: String
)

/**
 * Online search, backed by the Internet Archive's public advancedsearch.php API
 * (https://archive.org/advancedsearch.php) — real, documented, no API key needed.
 *
 * This is deliberately the ONLY search source wired up. qBittorrent's own Search tab uses a
 * plugin system whose bundled/most commonly installed plugins query sites whose indexes are
 * overwhelmingly unauthorized copies of copyrighted media (1337x, ThePirateBay-style
 * trackers, etc.) — building a scraper aimed at those isn't something to add here, since its
 * main use would be finding infringing content, not incidental to it. Internet Archive is a
 * legitimate library: every item returned is something its uploader chose to publish openly
 * (public domain works, Creative-Commons-licensed media, open-source software, etc.), and
 * every item automatically gets a real, working <identifier>_archive.torrent generated by
 * archive.org itself, so this integration is fully real end to end — search, results, and
 * the actual torrent download all come from the same legitimate source.
 */
object SearchManager {
    fun search(query: String, rows: Int = 25): List<SearchResult> {
        val encodedQuery = URLEncoder.encode(query, "UTF-8")
        val urlString = "https://archive.org/advancedsearch.php" +
            "?q=$encodedQuery" +
            "&fl%5B%5D=identifier&fl%5B%5D=title&fl%5B%5D=mediatype" +
            "&rows=$rows&page=1&output=json"

        val text = RssManager.fetchUrlTextPublic(urlString)
        val json = JSONObject(text)
        val docs = json.getJSONObject("response").getJSONArray("docs")

        val results = mutableListOf<SearchResult>()
        for (i in 0 until docs.length()) {
            val doc = docs.getJSONObject(i)
            val identifier = doc.optString("identifier", "")
            if (identifier.isBlank()) continue

            val title = doc.optString("title", identifier)
            val mediatype = doc.optString("mediatype", "")

            results.add(
                SearchResult(
                    identifier = identifier,
                    title = title,
                    mediatype = mediatype,
                    downloadUrl = "https://archive.org/download/$identifier/${identifier}_archive.torrent",
                    pageUrl = "https://archive.org/details/$identifier"
                )
            )
        }

        return results
    }
}